add_newline = false

[character]
disabled = false
success_symbol = "[ ➜](bold bright-green) "
error_symbol = "[ ✗](bold bright-red) "

[username]
disabled = false
show_always = true
style_user = "bold italic #87a752"
style_root = "bold italic red"
format = "[$user@]($style)"

[hostname]
disabled = false
ssh_only = false
trim_at = "."
style = "bold italic #87A752"
format = "[$hostname]($style) "

[aws]
disabled = true

[cmd_duration]
disabled = true

[package]
disabled = true

[rust]
disabled = false

[python]
disabled = true
