# starship zsh config
format = """\
    $username\
    $hostname\
    $directory\
    $git_branch\
    $git_commit\
    $git_state\
    $git_status\
    $cmake \
    $golang\
    $java\
    $rust\
    $swift\
    $line_break\
    $status\
    $character"""
add_newline = false

[character]
success_symbol = "[ ➜](bold bright-green)"
error_symbol   = "[ ✗](bold bright-red)"

[username]
format = "[$user@]($style)"
style_user  = "bold italic #87a752"
show_always = true

[hostname]
format = "[$hostname]($style) "
style  = "bold italic #87A752"
trim_at  = "."
ssh_only = false
